-- شغّل الملف بالكامل داخل Supabase > SQL Editor.
-- هذا لا يحذف bookings أو groups أو student_registrations.

create table if not exists public.teacher_feedback (
  id bigint generated by default as identity primary key,
  rating smallint not null check (rating between 1 and 5),
  positives text,
  negatives text,
  message text,
  created_at timestamptz not null default now()
);

alter table public.teacher_feedback enable row level security;

drop policy if exists "Anyone can submit feedback" on public.teacher_feedback;
drop policy if exists "Link admin can read feedback" on public.teacher_feedback;

-- الزائر يستطيع الإرسال.
create policy "Anyone can submit feedback"
on public.teacher_feedback for insert
to anon, authenticated
with check (true);

-- مطلوب لأن لوحة الأدمن في هذا الإصدار تعمل بالرابط فقط بدون تسجيل دخول.
-- تنبيه: الرابط المخفي ليس حماية حقيقية؛ أي شخص يحصل على anon key يمكنه القراءة بسبب هذه السياسة.
create policy "Link admin can read feedback"
on public.teacher_feedback for select
to anon
using (true);

grant insert, select on table public.teacher_feedback to anon;
grant usage, select on sequence public.teacher_feedback_id_seq to anon;

-- اختياري فقط إذا كنت متأكدًا أنك لم تعد تحتاج جدول التسجيل القديم:
-- drop table if exists public.student_registrations;
